### ISSUE TITLE
评论插件

### ISSUE THREAD

**Issue by xingchenxuup** [yuang01/hexo-theme-bamboo#16]
能集成下utteranc吗

**Comment by yuang01** [comment]
可以

**Comment by yuang01** [comment]
已经加上了

**Comment by xingchenxuup** [comment]
强啊大佬，速度真快

**Comment by xingchenxuup** [comment]
关于黑夜模式下该插件的主题色能否跟着变暗

**Comment by yuang01** [comment]
变暗的话，有时间我调一下

**Comment by yuang01** [comment]
utterance评论已经支持暗黑模式

**Comment by xingchenxuup** [comment]
![image](https://user-images.githubusercontent.com/76467253/130011538-de1e3fc4-f384-4479-8e45-cc791f89d745.png)

**Comment by yuang01** [comment]
![image](https://user-images.githubusercontent.com/32896990/130014516-9d53aaf5-4b7a-4df2-b14b-a2ba3d18f032.png)
是好的，有啥问题吗？

**Comment by xingchenxuup** [comment]
我忘了改配置 不好意思
