### ISSUE TITLE
There will be some mistakes to path of image when "post_asset_folder"  is true on root config.

### ISSUE THREAD

**Issue by alpaca0x0** [yuang01/hexo-theme-bamboo#18]
當 root config 下的 "**post_asset_folder**" 為 true 時，hexo 會將每篇文章生成獨立的 directory。
因此可以將該文章的圖檔放至文章所對應的 directory 中，但該主題似乎並未支持文章直接引入專屬目錄的圖檔。

**Comment by yuang01** [comment]
操作1：
将根目录的`post_asset_folder`属性设置为`true`

操作2：使用命令 

``` yaml
hexo new aaa
```

会在`source/_posts`文件夹下生成一个叫做`aaa`的文件夹和一个叫`aaa.md`的文件

操作3：例如将2.jpg，放入生成的`aaa`文件夹下，在`aaa.md`文件中使用如下方式引入图片
```md
---
title: aaa
date: 2021-08-20 14:03:20
tags:
---

![Image 22222](2.jpg)
```
是可以显示图片的

![image](https://user-images.githubusercontent.com/32896990/130188076-8a3ca2c6-b28f-47d6-9b93-3bff8d3a2888.png)

**Comment by yuang01** [comment]
具体请看
https://hexo.io/zh-cn/docs/asset-folders.html

**Comment by alpaca0x0** [comment]
更正，是文章 cover 的部份。

**Comment by yuang01** [comment]
这样图片在轮播图上是显示不了的
``` md
---
title: aaa
date: 2021-08-20 14:03:20
tags:
swiper: true
swiperImg: 2.jpg # 这样显示不了
---

![Image 22222](2.jpg)
```

需要在`source`下创建一个文件夹，例如叫`img`，这样写才能显示

``` md
---
title: aaa
date: 2021-08-20 14:03:20
tags:
swiper: true
swiperImg: /img/2.jpg
---

![Image 22222](2.jpg)
```

或者将图片放在主题文件夹`themes\hexo-theme-bamboo\source\medias`下

```md
---
title: Hexo主题--Bamboo介绍
date: 2020-09-14 14:06
swiper: true # 将改文章放入轮播图中
swiperImg: '/medias/1.jpg' 
img: '/medias/1.jpg'
categories: 前端
tags: [Hexo, hexo-theme-bamboo]
top: true

---
```

**Comment by alpaca0x0** [comment]
了解，非常感謝。
