### ISSUE TITLE
There is a problem with the Newcomer

### ISSUE THREAD

**Issue by dyingChinese** [yuang01/hexo-theme-bamboo#20]
I encountered the following problem:
`ERROR TypeError: D:\blog\themes\hexo-theme-bamboo\layout\index.ejs:21
    19|   </div>
    20|
 >> 21|   <%- partial('_partial/side') %>
    22| </div>
    23| 
    24| <%- partial('_partial/scripts/falling') %>

D:\blog\themes\hexo-theme-bamboo\layout\_partial\side.ejs:6
    4|     <% if (theme.sidebar.widget_library) { %>
    5|       <% if (theme.sidebar.widget_library.side_blogger.on) { %>
 >> 6|         <%- partial('side/side_blogger', { item: theme.sidebar.widget_library.side_blogger }) %>
    7|       <% } %>
    8|     <% } %>
    9|   <% } %>

D:\blog\themes\hexo-theme-bamboo\layout\_partial\side\side_blogger.ejs:31
    29|       <div class="social-wrapper">
    30|         <% (item.social||[]).forEach(function(value){ %>
 >> 31|           <% if (value.url && (value.icon || value.img || value.avatar)) { %>
    32|             <a href="<%= url_for(value.url) %>"
    33|               class="social <%- value.icon %> flat-btn"
    34|               target="_blank"

Cannot read properties of null (reading 'url')`

Because I was busy reporting during deployment, I didn't watch it.
In order to make it work, simply delete ``value.url'' so that it does not report an error.
`<% if (value && (value.icon || value.img || value.avatar)) { %>`
So I want to know about the error handling method of /side/
Your theme is very beautiful, I have sent you a star

**Comment by dyingChinese** [comment]
oh,shit Github,my code made  of dir
[github.md](https://github.com/yuang01/hexo-theme-bamboo/files/7489633/github.md)
ty

**Comment by yuang01** [comment]
感觉是侧边栏有问题，你侧边栏咋设置的
