### ISSUE TITLE
图片点击放大不能用

### ISSUE THREAD

**Issue by ChrisSpringLi** [yuang01/hexo-theme-bamboo#22]
图片可以正常显示，但不能点击放大
关键设置项：
* 主题配置文件中fancybox已经打开
```
# 图片点击放大功能
fancybox: 
  on: true
```
* hexo配置文件中
```

post_asset_folder: true
```
* markdown文件：
```
 ![](pic1.png)
```
目录结构
![image](https://user-images.githubusercontent.com/34155506/145511965-f02c9e33-7b90-45a3-ac38-ce41efd7a2b7.png)

**Comment by yuang01** [comment]
![(QEAVXD{)O2O DN$2_GM7DR](https://user-images.githubusercontent.com/32896990/145513556-2117a6f2-18d8-428d-96c5-015a56ff956a.png)
![3SQLHBZ_NFB9@TY{U0ZL%BT](https://user-images.githubusercontent.com/32896990/145513614-f6cd9fcd-4165-419f-aec7-17e6a20c607c.png)
![5)S}T51`D$2 UZID`B5AJFH](https://user-images.githubusercontent.com/32896990/145513669-742184dd-8663-44fa-80ae-3d08cc41b0a2.png)

http://localhost:4000/post/testimg/

我的可以显示的

**Comment by ChrisSpringLi** [comment]
没找到原因，重新建站，重新使用主题就好了
