### ISSUE TITLE
_config.yml里的tab和空格问题

### ISSUE THREAD

**Issue by Orange-Summer** [yuang01/hexo-theme-bamboo#26]
![image](https://user-images.githubusercontent.com/61171207/178888757-75eefcf1-0f2c-4b45-bbb5-8d0e8ffb85d4.png)
在337和339行这里，注释require后面用的是tab而不是空格，编辑器里没有设置tab自动替换为空格的话这句注释不会看作注释，可能有问题
大佬有空顺便看一下有没有影响吧

**Comment by yuang01** [comment]
感谢反馈，已更改
