### ISSUE TITLE
是否可以自己添加一个页面？

### ISSUE THREAD

**Issue by SaebaRyoo** [yuang01/hexo-theme-bamboo#39]
能否可以自己添加一个html页面，然后显示到首页的导航栏呢

**Comment by yuang01** [comment]
可以的，看文档的侧边栏那篇文章

**Comment by yuang01** [comment]
当然可以，在根目录下的`_config.yml`文件中找到`skip_render`属性，跳过渲染配置，用来配置/source/中需要跳过渲染的文件或目录，例如:`skip_render: projects/**`，具体请自行百度

**Comment by SaebaRyoo** [comment]
> 当然可以，在根目录下的`_config.yml`文件中找到`skip_render`属性，跳过渲染配置，用来配置/source/中需要跳过渲染的文件或目录，例如:`skip_render: projects/**`，具体请自行百度

好的，谢谢
