### ISSUE TITLE
官方文档有误

### ISSUE THREAD

**Issue by TianMiao8152** [yuang01/hexo-theme-bamboo#41]
该页面的缩进错误了
https://hexo-theme-bamboo.netlify.app/post/hexo-theme-bamboo/sidebar/
![2](https://github.com/yuang01/hexo-theme-bamboo/assets/83683108/70025c5e-f1dc-4fdb-88e2-5100c8941524)
![1](https://github.com/yuang01/hexo-theme-bamboo/assets/83683108/4eb4b6a9-16ce-4f9d-a0a9-68d0151f6a8f)

**Comment by yuang01** [comment]
y已更改
