### ISSUE TITLE
page.tags.length报undefined

### ISSUE THREAD

**Issue by songzhenze** [yuang01/hexo-theme-bamboo#5]
TypeError: \themes\hexo-theme-bamboo\layout\post.ejs:17
    15|       <% } %>
    16|       <div class="post-tags-categories">
 >> 17|         <% if (page.tags.length > 0) { %>
    18|         <div class="tags">
    19|           <i class="iconfont icontag"></i>
    20|           <% page.tags.map(function(tag) { %>

Cannot read property 'length' of undefined

是我哪里配置错了吗

**Comment by yuang01** [comment]
新建`/source/about/index.md`文件，至少需要以下内容
``` bash
---
title: about
date: 2020-09-14 15:30:30 # 时间随便写
type: "about"
layout: "about"
---
```
