### ISSUE TITLE
文章摘要功能

### ISSUE THREAD

**Issue by NongGuangXin** [yuang01/hexo-theme-bamboo#7]
建议参考hexo-theme-matery在Front-matter中增加一个 summary 摘要选项，然后首页浏览文章时显示文章摘要而不是文章内容。

**Comment by yuang01** [comment]
现在使用的是截取上面的部分，或者是文章内容，加一个summary 参数也行

**Comment by yuang01** [comment]
现在使用的是`<!-- more -->`上面的部分，或者文章内容，以后会考虑加上summary 参数的

**Comment by yuang01** [comment]
可以用excerpt，例如
```bash
excerpt: '这是一段介绍'
```
这个之前是有的，文档里忘写了，我自己都搞忘了
